### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by 2blponeyy** [vandalise/Discord-Token-Generator-V2#1]
ur token gen is not working

**Comment by vandalise** [comment]
whats wrong with it? make sure u have all modules installed. its working for me

**Comment by 2blponeyy** [comment]
![image](https://user-images.githubusercontent.com/89246972/218214374-8cfaf131-5b13-4cb0-b62e-32557ec82995.png)
 blocked here i paid proxy & key not creating tokens tho help please

**Comment by 2blponeyy** [comment]
![image](https://user-images.githubusercontent.com/89246972/218223695-8d12055b-ba21-4a13-a7dd-27ed4a09df05.png)
 now its working but not joining tokens
