### ISSUE TITLE
Dumb ass

### ISSUE THREAD

**Issue by Chrxst01** [vandalise/Discord-Token-Generator-V2#3]
Welcome herod, a 14 year old boy from texas. 

herod, refused to work. did not work for three days due to "being tired".  i worked for three days, to be told im doing "everything wrong" and that i was stupid. after a week of him putting in no effort, i fired him. i told him he could work on a separate project, while i get this one finished. he responded by utilising the trust i gave him to nuke the server, by hand as he cant code for his life. 

herod, i hope you get better, and start taking your medication.

**Comment by Turkisec** [comment]
interesting , so your project use tls/ja3 spoofing i am new to token gen and i am trying to find smart group to work with but until now i only found toxic kid and skids i have good project for discord i got one to gen a ja3 hash each time they change the certificate but i am stuck the tokens when gen they are unlocked but the the sec they join a server or send a friend requset or open dm the get locked

**Comment by vandalise** [comment]
lol so you took my code and sold it claiming u made it? I made 99% of surgecord lmao u shouldve never had ownership of the server. only reason u banned me is cuz u wanted to take the profits so i got the gen patched

**Comment by Turkisec** [comment]
> lol so you took my code and sold it claiming u made it? I made 99% of surgecord lmao u shouldve never had ownership of the server. only reason u banned me is cuz u wanted to take the profits so i got the gen patched

what is your discord

**Comment by ijnrghjkdsmigywneig203** [comment]
> lol so you took my code and sold it claiming u made it? I made 99% of surgecord lmao u shouldve never had ownership of the server. only reason u banned me is cuz u wanted to take the profits so i got the gen patched

stfu skid
